name: Terraform Develop - Plan & Apply

on:
  pull_request:
    branches: [ develop ]
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform Action'
        required: true
        default: apply
        type: choice
        options:
          - apply
          - plan

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: read

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    environment: ${{ (github.event_name == 'pull_request' && github.base_ref == 'develop') && 'develop' || github.ref_name }}

    env:
      TF_VERSION: '1.11.4'
      AWS_REGION: ${{ vars.AWS_REGION }}
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
      DEPLOY_LAMBDA: ${{ vars.DEPLOY_LAMBDA }}
      TF_IN_AUTOMATION: "true"
      TERM: xterm-256color

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 3600

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # - name: Generate backend and variables
      #   run: |
      #     make init
      #     make prepare

      - name: Terraform Init
        run: |
          terraform init 2>&1 | tee init_output.txt
          INIT_EXIT_CODE=${PIPESTATUS[0]}
          cat init_output.txt >> terraform.log
          if [ "$INIT_EXIT_CODE" -ne 0 ]; then
            echo "Terraform init failed."
            exit 1
          fi
        continue-on-error: true


      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'plan')
        continue-on-error: true
        run: |
          terraform plan -out=tfplan -detailed-exitcode 2>&1 | tee plan_output.txt
          PLAN_EXIT_CODE=${PIPESTATUS[0]}
          cat plan_output.txt >> terraform.log
          echo "--- END OF PLAN ---" >> terraform.log
          if [ "$PLAN_EXIT_CODE" -ne 0 ]; then
            echo "Terraform plan failed."
            exit 1
          fi
          
          terraform show -no-color tfplan > plan_readable.txt || true

          grep -E '^  # |Plan: |No changes.' plan_output.txt | nl > plan_summary.txt

          echo "PLAN_OUTPUT<<EOF" >> $GITHUB_ENV
          echo "Terraform Plan Summary:" >> $GITHUB_ENV
          echo "\`\`\`diff" >> $GITHUB_ENV
          cat plan_summary.txt >> $GITHUB_ENV
          echo "\`\`\`" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          if [ "${PIPESTATUS[0]}" -eq 1 ]; then
            echo "::error::Terraform plan failed"
            exit 1
          fi

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
          retention-days: 30
          compression-level: 6

      - name: Comment plan on PR
        if: github.event_name == 'pull_request'
        continue-on-error: true
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN_GITHUB }}
          script: |
            const planSummary = process.env.PLAN_OUTPUT;
            const fullPlan = require('fs').readFileSync('plan_readable.txt', 'utf8');

            const comment = `
            ### üîç Terraform Plan Results

            ${planSummary}

            <details><summary>üí¨ View Full Terraform Plan</summary>

            \`\`\`hcl
            ${fullPlan}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Event: \`${{ github.event_name }}\`*`;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(c =>
              c.user.type === 'Bot' && c.body.includes('Terraform Plan Results')
            );

            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: comment
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: comment
              });
            }

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply'
        run: |
          terraform apply -auto-approve 2>&1 | tee apply_output.txt
          APPLY_EXIT_CODE=${PIPESTATUS[0]}
          cat apply_output.txt >> terraform.log
          echo "--- END OF APPLY ---" >> terraform.log
          if [ "$APPLY_EXIT_CODE" -ne 0 ]; then
            echo "Terraform apply failed."
            exit 1
          fi
        continue-on-error: true
      
      # - uses: actions/cache@v1
      #   id: cache
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-dependencies
      #     restore-keys: |
      #       ${{ runner.os }}-pip-

      # - name: Install Python Dependencies
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   run: |
      #     pip install chromadb openai tiktoken langchain-community langchain unstructured langchain-openai

      # - name: Install Python Dependencies on Failure
      #   if: steps.init.outcome == 'failure' || steps.plan.outcome == 'failure' || steps.apply.outcome == 'failure'
      #   run: |
      #     pip install chromadb openai tiktoken langchain-community langchain unstructured langchain-openai

      - name: Write dependencies to file
        run: |
          echo "chromadb openai tiktoken langchain-community langchain unstructured langchain-openai python-hcl2" > dependencies.txt

      - uses: actions/cache@v4
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('dependencies.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python Dependencies
        if: steps.init.outcome == 'failure' || steps.plan.outcome == 'failure' ||  steps.apply.outcome == 'failure'
        run: pip install chromadb openai tiktoken langchain-community langchain unstructured langchain-openai python-hcl2

      - name: Run AI Analyzer on Failure
        if: steps.init.outcome == 'failure' || steps.plan.outcome == 'failure' ||  steps.apply.outcome == 'failure'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p logs
          cp terraform.log logs/terraform.log || echo "No log available"
          echo "‚ö†Ô∏è Terraform Apply failed. Running analysis script..."
          python test.py

      - name: Fail CI run if Apply failed
        if: steps.init.outcome == 'failure' || steps.plan.outcome == 'failure' ||  steps.apply.outcome == 'failure'
        run: |
          echo "‚ùå Marking the workflow as failed due to Terraform Apply failure."
          exit 1

      #       - name: Install Infracost
      #         if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'plan')
      #         run: |
      #           terraform show -json tfplan > plan.json
      #           curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
      #           echo "$HOME/.infracost/bin" >> $GITHUB_PATH

      #       - name: Run Infracost
      # #        if: github.event.inputs.action == 'push'
      #         env:
      #           INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
      #         run: |
      #           infracost breakdown --path .
      #           infracost breakdown --path . --format json --out-file infracost.json

      # - name: Run Infracost on diff
      #   if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'plan')
      #   env:
      #     INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
      #   run: |
      #     infracost breakdown --path . --format json --out-file infracost-develop-pr.json

      # - name: Check diff infracost
      #   if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'plan')
      #   env:
      #     INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
      #   run: |
      #     git fetch origin infracost
      #     git checkout origin/infracost -- "infracost-develop-pr.json"
      #     infracost diff --path . --compare-to infracost-develop-pr.json
      

      # push the changes to github branch.
      # - name: Set up Git
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"

      # - name: Get branch name (push or PR)
      #   id: extract_branch
      #   run: |
      #     if [[ "${{ github.event_name }}" == "pull_request" ]]; then
      #       echo "branch_name=${{ github.event.pull_request.base.ref }}-pr" >> "$GITHUB_OUTPUT"
      #     else
      #       BRANCH_NAME="${GITHUB_REF#refs/heads/}"
      #       echo "branch_name=$BRANCH_NAME" >> "$GITHUB_OUTPUT"
      #     fi

      # - name: Create/switch to environment branch
      #   run: |
      #     git checkout -B infracost

      # - name: Copy Infracost JSON to correct filename
      #   run: |
      #     FILENAME="infracost-${{ steps.extract_branch.outputs.branch_name }}.json"
      #     cp ./infracost.json "./$FILENAME"

      # - name: Commit Infracost JSON to infracost branch
      #   run: |
      #     FILENAME="infracost-${{ steps.extract_branch.outputs.branch_name }}.json"
      #     git add "$FILENAME"
      #     git commit -m "Update $FILENAME [skip ci]" || echo "No changes to commit"

      # - name: Push to environment branch
      #   run: |
      #     git push origin infracost --force

      # - name: Show cost estimate
      #   run: |
      #     cat infracost-output.json

      #      - name: Analyze Terraform Errors with OpenAI
      #        env:
      #          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #        run: python terraform-analyzer.py

      #      - name: Trigger Cost Analyzer
      #        if: success() && (github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'plan'))
      #        run: |
      #          echo "Triggering cost analyzer workflow..."
      #          echo "Run ID: $GITHUB_RUN_ID"
      #          echo "Repository: $GITHUB_REPOSITORY"
      #
      #          gh workflow run "Terraform Analyzer" \
      #            --field source_run_id="$GITHUB_RUN_ID" \
      #            --field source_repository="$GITHUB_REPOSITORY"
      #        env:
      #          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      - name: Set up GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Trigger Terraform Analyzer
        run: |
          gh workflow run "Terraform cost analyzer" \
            --ref main \
            --field source_run_id="${{ github.run_id }}" \
            --field source_repository="${{ github.repository }}"
